// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Loading: typeof import('./src/components/loading.vue')['default']
    Nav: typeof import('./src/components/nav.vue')['default']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    Tabbar: typeof import('./src/components/tabbar.vue')['default']
    Toast: typeof import('./src/components/toast.vue')['default']
  }
}
